### ISSUE TITLE
BLAST bug

### ISSUE THREAD

**Issue by ruribev** [nijnstein/BLAST-Documentation#3]
Hello,

BLAST look awesome and is perfect for my project. I am doing a big csv editor and wanna do some basic math operation between different columns so I was loading the "Sample 10 - Example - SSMD Statemachine" and got the following errors:

map_identifiers: identifier 'select' is not constant and not defined in input and as such is undefined.
UnityEngine.Debug:LogError (object)
NSS.Blast.Compiler.CompilationData:LogError (string,int,int,string) (at Assets/BLAST/BLAST/Source/Compiler/Stages/CompilationData.cs:337)
NSS.Blast.Compiler.Stage.BlastIdentifierMapping:map_identifiers (NSS.Blast.Compiler.IBlastCompilationData,NSS.Blast.Compiler.node) (at Assets/BLAST/BLAST/Source/Compiler/Stages/BlastIdentifierMapping.cs:324)
NSS.Blast.Compiler.Stage.BlastIdentifierMapping:map_identifiers (NSS.Blast.Compiler.IBlastCompilationData,NSS.Blast.Compiler.node) (at Assets/BLAST/BLAST/Source/Compiler/Stages/BlastIdentifierMapping.cs:413)
NSS.Blast.Compiler.Stage.BlastIdentifierMapping:map_identifiers (NSS.Blast.Compiler.IBlastCompilationData,NSS.Blast.Compiler.node) (at Assets/BLAST/BLAST/Source/Compiler/Stages/BlastIdentifierMapping.cs:413)
NSS.Blast.Compiler.Stage.BlastIdentifierMapping:Execute (NSS.Blast.Compiler.IBlastCompilationData) (at Assets/BLAST/BLAST/Source/Compiler/Stages/BlastIdentifierMapping.cs:438)
NSS.Blast.Compiler.BlastCompiler:Compile (NSS.Blast.BlastEngineDataPtr,NSS.Blast.BlastScript,NSS.Blast.Compiler.BlastCompilerOptions) (at Assets/BLAST/BLAST/Source/Compiler/BlastCompiler.cs:1239)
NSS.Blast.BlastScript:Prepare (intptr,bool,bool) (at Assets/BLAST/BLAST/Source/Packaging/BlastScript.cs:168)
NSS.Blast.BlastScript:Prepare (bool,bool) (at Assets/BLAST/BLAST/Source/Packaging/BlastScript.cs:142)
Sample10:CompileScripts () (at Assets/BLAST/DEMO Scenes/Sample 10 - Example - SSMD Statemachine/Sample10.cs:118)
Sample10:Start () (at Assets/BLAST/DEMO Scenes/Sample 10 - Example - SSMD Statemachine/Sample10.cs:109)

blast.compiler.identifiermapping: failed to map all identifiers
UnityEngine.Debug:LogError (object)
NSS.Blast.Compiler.CompilationData:LogError (string,int,int,string) (at Assets/BLAST/BLAST/Source/Compiler/Stages/CompilationData.cs:337)
NSS.Blast.Compiler.Stage.BlastIdentifierMapping:Execute (NSS.Blast.Compiler.IBlastCompilationData) (at Assets/BLAST/BLAST/Source/Compiler/Stages/BlastIdentifierMapping.cs:440)
NSS.Blast.Compiler.BlastCompiler:Compile (NSS.Blast.BlastEngineDataPtr,NSS.Blast.BlastScript,NSS.Blast.Compiler.BlastCompilerOptions) (at Assets/BLAST/BLAST/Source/Compiler/BlastCompiler.cs:1239)
NSS.Blast.BlastScript:Prepare (intptr,bool,bool) (at Assets/BLAST/BLAST/Source/Packaging/BlastScript.cs:168)
NSS.Blast.BlastScript:Prepare (bool,bool) (at Assets/BLAST/BLAST/Source/Packaging/BlastScript.cs:142)
Sample10:CompileScripts () (at Assets/BLAST/DEMO Scenes/Sample 10 - Example - SSMD Statemachine/Sample10.cs:118)
Sample10:Start () (at Assets/BLAST/DEMO Scenes/Sample 10 - Example - SSMD Statemachine/Sample10.cs:109)

Blast Compilation Error: stage: 2, type BlastIdentifierMapping, exitcode: -50
UnityEngine.Debug:LogError (object)
NSS.Blast.Compiler.CompilationData:LogError (string,int,int,string) (at Assets/BLAST/BLAST/Source/Compiler/Stages/CompilationData.cs:337)
NSS.Blast.Compiler.BlastCompiler:Compile (NSS.Blast.BlastEngineDataPtr,NSS.Blast.BlastScript,NSS.Blast.Compiler.BlastCompilerOptions) (at Assets/BLAST/BLAST/Source/Compiler/BlastCompiler.cs:1244)
NSS.Blast.BlastScript:Prepare (intptr,bool,bool) (at Assets/BLAST/BLAST/Source/Packaging/BlastScript.cs:168)
NSS.Blast.BlastScript:Prepare (bool,bool) (at Assets/BLAST/BLAST/Source/Packaging/BlastScript.cs:142)
Sample10:CompileScripts () (at Assets/BLAST/DEMO Scenes/Sample 10 - Example - SSMD Statemachine/Sample10.cs:118)
Sample10:Start () (at Assets/BLAST/DEMO Scenes/Sample 10 - Example - SSMD Statemachine/Sample10.cs:109)

I am using Unity 2021.2.10f and burst 1.7.0

![error](https://user-images.githubusercontent.com/43749547/161451430-8bb620fe-e9bd-429d-805c-be71454b9bfe.jpg)

**Comment by nijnstein** [comment]
Hi, Thanks for taking the time to log this issue:

- The first version is a little rough, we appologise for that. A new version 1.0.2 is uploaded to unity and will be released into the asset store hopefully monday. 

-There is also a bug in release builds but that is not your problem it seems. 

That said, the sample should work out of the box. Its as if blast is initialized without the scriptapi added to it. 

Is there is no change in code?

**Comment by nijnstein** [comment]
Could you show me the output of a log message you should have in your log called "BLAST: Known script functions:"

It should look like: 


BLAST: known script functions: 

 Index    FID   FunctionName                     Operation    Extended Op  
--------------------------------------------------------------------------------
     3      3   yield                            yield        nop         
     4      4   pop                              pop          nop         
     5      5   peek                             peek         nop         
     6      6   seed                             seed         nop         
     7      7   push                             push         nop         
     8      8   pushf                            pushf        nop         
     9      9   pushc                            pushc        nop         
    10     10   pushv                            pushv        nop         
    11     11   debug                            ex_op        debug       
    12     12   debugstack                       ex_op        debugstack  
    13     13   validate                         ex_op        validate    
    32     32   return                           ret          nop         
    33     33   abs                              abs          nop         
    34     34   min                              min          nop         
    35     35   max                              max          nop         
    36     36   mina                             mina         nop         
    37     37   maxa                             maxa         nop         
    38     38   any                              any          nop         
    39     39   all                              all          nop         
    40     40   adda                             adda         nop         
    41     41   suba                             suba         nop         
    42     42   diva                             diva         nop         
    43     43   mula                             mula         nop         
    44     44   fma                              fma          nop         
    45     45   fmod                             ex_op        fmod        
    46     46   trunc                            trunc        nop         
    47     47   csum                             csum         nop         
    48     48   select                           select       nop         
    49     49   random                           random       nop         
    50     50   idx                              index_x      nop         
    51     51   idy                              index_y      nop         
    52     52   idz                              index_z      nop         
    53     53   idw                              index_w      nop         
    54     54   expand2                          expand_v2    nop         
    55     55   expand3                          expand_v3    nop         
    56     56   expand4                          expand_v4    nop         
    57     57   sin                              ex_op        sin         
    58     58   cos                              ex_op        cos         
    59     59   tan                              ex_op        tan         
    60     60   atan                             ex_op        atan        
    61     61   atan2                            ex_op        atan2       
    62     62   cosh                             ex_op        cosh        
    63     63   sinh                             ex_op        sinh        
    64     64   degrees                          ex_op        degrees     
    65     65   rad                              ex_op        radians     
    66     66   sqrt                             ex_op        sqrt        
    67     67   rsqrt                            ex_op        rsqrt       
    68     68   pow                              ex_op        pow         
    69     69   normalize                        ex_op        normalize   
    70     70   saturate                         ex_op        saturate    
    71     71   clamp                            ex_op        clamp       
    72     72   log2                             ex_op        log2        
    73     73   log10                            ex_op        log10       
    74     74   log                              ex_op        logn        
    75     75   exp                              ex_op        exp         
    76     76   exp10                            ex_op        exp10       
    77     77   cross                            ex_op        cross       
    78     78   dot                              ex_op        dot         
    79     79   ceil                             ex_op        ceil        
    80     80   floor                            ex_op        floor       
    81     81   frac                             ex_op        frac        
    82     82   lerp                             ex_op        lerp        
    83     83   slerp                            ex_op        slerp       
    84     84   nlerp                            ex_op        nlerp       
    85     85   unlerp                           ex_op        unlerp      
    86     86   remap                            ex_op        remap       
    87     87   ceillog2                         ex_op        ceillog2    
    88     88   floorlog2                        ex_op        floorlog2   
    89     89   ceilpow2                         ex_op        ceilpow2    
    90     90   set_bits                         set_bits     nop         
    91     91   set_bit                          set_bit      nop         
    92     92   get_bits                         get_bits     nop         
    93     93   get_bit                          get_bit      nop         
    94     94   count_bits                       ex_op        count_bits  
    95     95   reverse_bits                     ex_op        reverse_bits
    96     96   shl                              ex_op        shl         
    97     97   shr                              ex_op        shr         
    98     98   rol                              ex_op        rol         
    99     99   ror                              ex_op        ror         
   100    100   lzcnt                            ex_op        lzcnt       
   101    101   tzcnt                            ex_op        tzcnt       
   102    102   zero                             zero         nop         
   103    103   clear_bits                       zero         nop         
   104    104   reinterpret_bool32               ex_op        reinterpret_bool32
   105    105   reinterpret_float32              ex_op        reinterpret_float
--------------------------------------------------------------------------------


UnityEngine.Debug:Log (object)
NSS.Blast.Blast:Create (NSS.Blast.BlastScriptAPI,Unity.Collections.Allocator) (at Assets/BLAST/BLAST/Source/Blast.cs:572)
NSS.Blast.Blast:Initialize (NSS.Blast.BlastScriptAPI) (at Assets/BLAST/BLAST/Source/Blast.cs:409)
Sample10:Start () (at Assets/BLAST/DEMO Scenes/Sample 10 - Example - SSMD Statemachine/Sample10.cs:76)



Select should be present in this list, if not something is going wrong during initialization

**Comment by ruribev** [comment]
Thanks for the quick reply! Don't worry, I can wait for the update. 

I want to take the opportunity to say that the concept of BLAST seems incredible to me and it is something that I had thought of doing in a much simpler way. 

My main concerns right now are the following:

- How efficient it is on large datasets like 1 million floats.
- And for my particular case I have datasets with integers and doubles and I was wondering if there is a way to deal with these cases with BLAST in a simple way? 

I would appreciate it if you could give me some head start on how to deal with these cases so that when I start to see more of BLAST in detail, I can understand better how to do this cases. 

Thanks in advance for the support and I see with great emotion what can be done with BLAST
