### ISSUE TITLE
Sample6 bug error after update

### ISSUE THREAD

**Issue by ruribev** [nijnstein/BLAST-Documentation#6]
Hello,

I was looking Sample 6 after the last update and got some errors:

![sample6](https://user-images.githubusercontent.com/43749547/161558391-4fccf072-5bb9-43f9-becf-f5cce3b2f22f.jpg)

It was working before without a problem.

All the best,
Rodrigo

**Comment by ruribev** [comment]
Awesome, now is working without a problem. Thanks!

**Comment by nijnstein** [comment]
well we have unittests running in visualstudio but they dont cover some specific pieces, this illustrates why that is going to be priority now
