### ISSUE TITLE
Android Build

### ISSUE THREAD

**Issue by ruribev** [nijnstein/BLAST-Documentation#9]
Hello!

I am not sure if Blast is intended to run on android. I am doing a fun project and was tryng it out:
![image](https://user-images.githubusercontent.com/43749547/162364308-733f0f4e-6895-4285-b7f7-629e5c17e981.png)

In case this is something that you are looking to accomplish I can help with doing some tests.

Cheers,
Rodrigo

**Comment by nijnstein** [comment]
Well ive never tried on android but will get to it someday.

**Comment by nijnstein** [comment]
It looks like some conditional defines go out of order but besides that it should probably work, there is not anything special for windows in it.

**Comment by nijnstein** [comment]
i has the same issue on a webgl build, this is fixed for the next release in a few days
